library(lubridate)
hhold <- read.csv("household_power_consumption.txt", sep=";", stringsAsFactors=FALSE)
hholdFeb <- hhold[hhold$Date=="1/2/2007" | hhold$Date=="2/2/2007",]
hholdFeb[,3] <- as.numeric(as.character(hholdFeb[,3]))
hholdFeb[,4] <- as.numeric(as.character(hholdFeb[,4]))
hholdFeb[,5] <- as.numeric(as.character(hholdFeb[,5]))
hholdFeb[,7] <- as.numeric(as.character(hholdFeb[,7]))
hholdFeb[,8] <- as.numeric(as.character(hholdFeb[,8]))
hholdFeb[,9] <- as.numeric(as.character(hholdFeb[,9]))
startInst <- unclass(parse_date_time("1/2/2007 00:00:00", "dmyhms"))
hholdFeb$t <- (unclass(parse_date_time(paste(hholdFeb$Date,hholdFeb$Time), "dmyhms"))-startInst)/60
par(mfrow=c(2,2), cex=0.6)
plot(hholdFeb$t, hholdFeb$Global_active_power, type="l", xlab="", ylab="Global Active Power",xaxt="n")
axis(1,at=c(0,1440,2880),labels=c("Thu", "Fri", "Sat") )
plot(hholdFeb$t, hholdFeb$Voltage, type="l", xlab="datetime", ylab="Voltage",xaxt="n")
axis(1,at=c(0,1440,2880),labels=c("Thu", "Fri", "Sat") )
plot(hholdFeb$t, hholdFeb$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering", xaxt="n")
axis(1,at=c(0,1440,2880),labels=c("Thu", "Fri", "Sat") )
lines(hholdFeb$t, hholdFeb$Sub_metering_2, col="red")
lines(hholdFeb$t, hholdFeb$Sub_metering_3, col="blue")
legend(1300,40,c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty="n", lty=c(1,1,1), lwd=c(2.5,2.5,2.5), col=c("black", "red", "blue"))
plot(hholdFeb$t, hholdFeb$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power",xaxt="n")
axis(1,at=c(0,1440,2880),labels=c("Thu", "Fri", "Sat") )
dev.copy(png,"plot4.png")
dev.off()